# Generated by Django 5.2.4 on 2025-08-09 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contribution_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contribution',
            unique_together=set(),
        ),
    ]
