# Generated by Django 5.2.4 on 2025-08-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_contribution_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='fee_rate',
            field=models.DecimalField(decimal_places=4, default=0.05, max_digits=5),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_fees_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
