# Generated by Django 5.2.4 on 2025-08-22 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customer_fee_rate_customer_total_fees_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='fee_rate',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='total_fees_paid',
        ),
    ]
